[general]
# An experiment is a method (rf, perm, var, mst, imp_con, corsum) applied to a 
#   collection (msmarco, dbpedia, etc.) with a specific model (ance, distilbert, bge, etc.)
# To enabled the compute of an experiment, list in enabled_experiments the names of the experiments you want to compute,
#   separated by commas. For each experiment, there must be a section in this ini file
#   with the name [experiments.<experiment_name>]
enabled_experiments = msmarco-bge-small-rf, dbpedia-ance-rf
# other experiments previously computed
# enabled_experiments = msmarco-bge-small-imp_con, dbpedia-ance-imp_con

# Logger configuration
[logging]
dir = logs/
preffix = compute_evaluation
verbose = False

[experiments.msmarco-bge-small-rf]
name = msmarco-bge small RF
runs_dir = runs/
qrels_file  = ../collections/msmarco-passages-ranking/qrels.dev.small.tsv
preffix = msmarco_dev_small-bge-small..flatIP.nq-False.k100.rf


[experiments.msmarco-bge-small-imp_con]
name = msmarco-bge small IMP CON
runs_dir = runs/
qrels_file  = ../collections/msmarco-passages-ranking/qrels.dev.small.tsv
preffix = msmarco_dev_small-bge-small..flatIP.nq-False.k100.imp_con


[experiments.dbpedia-ance-imp_con]
name = dbpedia-ance IMP CON
runs_dir = runs/
qrels_file  = ../collections/dbpedia-entity/qrels/test.tsv
qrels_format = dbpedia
preffix = dbpedia_queries-ance..flatIP.nq-False.k100.imp_con


[experiments.dbpedia-ance-rf]
name = dbpedia-ance RF
runs_dir = runs/
qrels_file  = ../collections/dbpedia-entity/qrels/test.tsv
qrels_format = dbpedia
preffix = dbpedia_queries-ance..flatIP.nq-False.k100.rf

